// <auto-generated />
using System;
using LanguageSchoolManagementSystem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LanguageSchoolManagementSystem.Data.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210129153844_sixth")]
    partial class sixth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Attendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentOwnerUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttendanceId");

                    b.HasIndex("StudentOwnerUserID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.AttendanceEntry", b =>
                {
                    b.Property<Guid>("AttendanceEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEntry")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceEntryId");

                    b.HasIndex("AttendanceId");

                    b.ToTable("AttendanceEntries");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassId");

                    b.HasIndex("TeacherUserID");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = new Guid("692e3dc0-862b-4cdc-874e-ea3692becc78"),
                            ClassName = "3A BEST OF"
                        });
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.CredentialsContainer", b =>
                {
                    b.Property<Guid>("CredentialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialsId");

                    b.ToTable("CredentialsContainers");

                    b.HasData(
                        new
                        {
                            CredentialsId = new Guid("61ed95e5-3623-4bf5-bc06-c0ff482bc23f"),
                            Email = "D@starzyk.pl",
                            Login = "Dodos93",
                            Password = "Dodos93"
                        },
                        new
                        {
                            CredentialsId = new Guid("34781758-f9e1-48c2-b632-693304019e66"),
                            Email = "K@wojcik.pl",
                            Login = "Wojcik93",
                            Password = "Wojcik93"
                        },
                        new
                        {
                            CredentialsId = new Guid("9637922f-6201-4723-886a-add460e867ec"),
                            Email = "Jarek",
                            Login = "Jarek",
                            Password = "Jarek"
                        });
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("CredentialsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("CredentialsId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Student", b =>
                {
                    b.HasBaseType("LanguageSchoolManagementSystem.Data.Entities.Users.User");

                    b.Property<Guid?>("CurrentClassClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CurrentClassClassId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Teacher", b =>
                {
                    b.HasBaseType("LanguageSchoolManagementSystem.Data.Entities.Users.User");

                    b.HasDiscriminator().HasValue("Teacher");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("ed7344a1-0333-4db8-88de-52b9739bf6f4"),
                            AccessLevel = 1,
                            Age = 27,
                            Name = "Adrian",
                            Surname = "Starzyk"
                        },
                        new
                        {
                            UserID = new Guid("5ecffa2e-cd9e-48ab-9091-9d0ceb133254"),
                            AccessLevel = 1,
                            Age = 37,
                            Name = "Kamil",
                            Surname = "Wójcik"
                        });
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Attendance", b =>
                {
                    b.HasOne("LanguageSchoolManagementSystem.Data.Entities.Users.Student", "StudentOwner")
                        .WithMany()
                        .HasForeignKey("StudentOwnerUserID");

                    b.Navigation("StudentOwner");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.AttendanceEntry", b =>
                {
                    b.HasOne("LanguageSchoolManagementSystem.Data.Entities.Users.Attendance", null)
                        .WithMany("AttendanceHistory")
                        .HasForeignKey("AttendanceId");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Class", b =>
                {
                    b.HasOne("LanguageSchoolManagementSystem.Data.Entities.Users.Teacher", null)
                        .WithMany("ClassesAssigned")
                        .HasForeignKey("TeacherUserID");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.User", b =>
                {
                    b.HasOne("LanguageSchoolManagementSystem.Data.Entities.Users.CredentialsContainer", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Student", b =>
                {
                    b.HasOne("LanguageSchoolManagementSystem.Data.Entities.Users.Class", "CurrentClass")
                        .WithMany("StudentsInClass")
                        .HasForeignKey("CurrentClassClassId");

                    b.Navigation("CurrentClass");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Attendance", b =>
                {
                    b.Navigation("AttendanceHistory");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Class", b =>
                {
                    b.Navigation("StudentsInClass");
                });

            modelBuilder.Entity("LanguageSchoolManagementSystem.Data.Entities.Users.Teacher", b =>
                {
                    b.Navigation("ClassesAssigned");
                });
#pragma warning restore 612, 618
        }
    }
}
